apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "k8s-nfs-provisioner.name" . }}
    helm.sh/chart: {{ include "k8s-nfs-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "k8s-nfs-provisioner.svcaccountname" . }}
  namespace: {{ .Release.Namespace }}
