{{- $appname := include "fullapp.name" . -}}
{{- range .Values.networkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ $appname }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ $appname }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      {{- with .podSelector }}
        {{- toYaml . | nindent 6 }}
      {{- end -}}
  {{- with .policyTypes }}
  policyTypes:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
  {{- with .ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
  {{- with .egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
{{ end -}}