{{- if eq "Deployment" .Values.deployment.kind }}
{{- range $pvc := .Values.persistentVolumeClaims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $.Release.Name }}-{{$pvc.name}}"
  {{- with $pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml $pvc.spec | nindent 2 -}}
{{- end }}
{{- end }}
