{{- $appfullname := include "fullapp.fullname" . -}}
{{- $appname := include "fullapp.name" . -}}
{{- $chartname := include "fullapp.chart" . -}}
{{- $roleType := .Values.pod.serviceAccount.roleType -}}
{{- $bindingType := .Values.pod.serviceAccount.bindingType -}}
{{- $accountName := include "serviceaccount-name" . -}}

{{/*
Cria o service account somente se o nome definido não for "default".
*/}}
{{ if and (.Values.pod.serviceAccount.create) (not (eq $accountName "default")) -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: {{ $accountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $appname }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

{{ if .Values.pod.serviceAccount.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $roleType }}
metadata:
  name: {{ $accountName }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $appname }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  {{- toYaml .Values.pod.serviceAccount.rules  | nindent 2 }}

---
kind: {{ $bindingType }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $accountName }}-binding
  labels:
    app.kubernetes.io/name: {{ $appname }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  kind: {{ $roleType }}
  name: {{ $accountName }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ $accountName }}
  namespace: {{ .Release.Namespace }}
{{ end }}

{{ end }}