{{- if and (.Values.service.enabled) (empty .Values.service.ports) -}}
  {{ required "SERVICE DOES NOT HAVE ANY PORTS DEFINED" nil }}
{{- end -}}

{{- if .Values.service.enabled -}}
{{- $appfullname := include "fullapp.fullname" . -}}
{{- $appname := include "fullapp.name" . -}}
{{- $chartname := include "fullapp.chart" . -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appfullname }}
  labels:
    app.kubernetes.io/name: {{ $appname }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
  {{- range . }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ coalesce .targetPort .name .port }}
      protocol: {{ default "TCP" .protocol }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
  {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ $appname }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}