{{- if .Values.filesystem }}
{{- range .Values.filesystem }}
---
apiVersion: v1
data:
  contents: {{ .contents | quote }}
kind: ConfigMap
metadata:
  name: "{{ $.Release.Name }}-{{ .name }}"
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart-version: "{{ .Chart.Version }}"
{{- end }}
{{- end }}