apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart-version: "{{ .Chart.Version }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
    {{- if .Values.servicePorts }}
    {{- range .Values.servicePorts }}
    - port: {{ .servicePort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
    {{- end }}
  externalTrafficPolicy: {{ .Values.externalTrafficPolicy }}
  {{- if .Values.loadBalancerExternalIPs }}
  # externalIPs:
  #   {{- range .Values.loadBalancerExternalIPs }}
  #   - {{ . }}
  #   {{- end }}
  # {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.loadBalancerExternalIPs }}
status:
  loadBalancer:
    ingress:
    {{- range .Values.loadBalancerExternalIPs }}
    - {{ . }}
    {{- end }}
{{- end }}
