image:
  repository: juliohm/k8s-nfs-provisioner
  tag: "1.2.6"
  pullPolicy: IfNotPresent

## Disable if you wish to provide your own serviceaccount with different permissions.
createServiceAccount: true

## This value will be prefixed with the release name to create a unique
## service account for each release.
serviceAccount: k8s-nfs-provisioner

nameOverride: ""
fullnameOverride: ""

## Disable this if you do not wish to (or cannot) run privileged Pods.
## PV Data Initialization will not be available and you might also
## want to set `args.disablePvInit: false`
privileged: true

args:
  ## Polling interval on the API server for PVC events.
  interval: 30

  ## Possible values: error, warning, info, debug
  debugLevel: info

  ## Restrict the controller reaction to a specific namespace.
  ## Leave empty to listen to all PVC events in the cluster.
  namespace:

  ## Disable PV Data Initalization (works along with the `privileged` flag above)
  disablePvInit: false

  ## Directory where nfs shares will be mounted for PV Data Initialization
  nfsroot: /mnt/nfs

  ## Force PV init without PVC annotations
  forcePvInit: false

## This should be enough resources to make it work.
## Feel free to change if necessary.
resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

## Declare your StorageClasses. These will be used to mount volumes
## into the controller to allow PV Data Initialization.
## Remember to use "nfs-provisioner.juliohm.com.br" as provisioner.
storageClasses: {}
  # - apiVersion: storage.k8s.io/v1
  #   kind: StorageClass
  #   metadata:
  #     name: sc01
  #   provisioner: nfs-provisioner.juliohm.com.br
  #   parameters:
  #     server: 10.10.0.3
  #     share: /myshare
  #     path: /subpath
  #   reclaimPolicy: Delete
  # - apiVersion: storage.k8s.io/v1
  #   kind: StorageClass
  #   metadata:
  #     name: sc02
  #   provisioner: nfs-provisioner.juliohm.com.br
  #   parameters:
  #     server: 10.10.0.3
  #     share: /myshare
  #     path: /subpath
  #   reclaimPolicy: Retain
