apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    {{- if .Values.servicePorts }}
    {{- range .Values.servicePorts }}
    - port: {{ .servicePort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
    {{- end }}
  {{- if .Values.loadBalancerExternalIPs }}
  externalIPs:
    {{- range .Values.loadBalancerExternalIPs }}
    - {{ . }}
    {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
